import java.awt.Dimension;

public class OptionsMenu extends javax.swing.JFrame {

    private newCreateQuestion cQuestion;
    private updateQuestion uQuestion;
    private StartMenu startMenu;

    /**
     * Creates new form OptionsMenu
     */
    public OptionsMenu() {
        initComponents();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        createQuestion = new javax.swing.JButton();
        updateQuestion = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        createQuestion.setText("Създай въпрос");
        createQuestion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createQuestionActionPerformed(evt);
            }
        });

        updateQuestion.setText("Редактирай въпрос");
        updateQuestion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateQuestionActionPerformed(evt);
            }
        });

        jButton1.setText("Назад");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(263, 263, 263)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(createQuestion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(updateQuestion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(218, 218, 218))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(createQuestion, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(updateQuestion, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(103, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        
    /**
     * 
     * @return the size of the current frame 
     */
    private Dimension getDimension(){
        return this.getSize();
    }
    
    /**
     * Opens a new menu
     * @param evt 
     */
    private void createQuestionActionPerformed(java.awt.event.ActionEvent evt) {                                               
          cQuestion = new newCreateQuestion();    
          cQuestion.setSize(getDimension());
          this.setVisible(false);
          cQuestion.setVisible(true);      
    }                                              
    
     /**
     * Opens a new menu
     * @param evt 
     */
    private void updateQuestionActionPerformed(java.awt.event.ActionEvent evt) {                                               
        uQuestion = new updateQuestion();
        uQuestion.setSize(getDimension());
        this.setVisible(false);
        uQuestion.setVisible(true);      
    }                                              
    
     /**
     * Opens a new menu
     * @param evt 
     */
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        startMenu = new StartMenu();
        startMenu.setVisible(true);
        startMenu.setSize(getDimension());
        this.setVisible(false);
    }                                        

    // Variables declaration - do not modify                     
    private javax.swing.JButton createQuestion;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton updateQuestion;
    // End of variables declaration                   
}
